kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vsphere-csi
provisioner: csi.vsphere.vmware.com
parameters:
  datastoreurl: "ds:///vmfs/volumes/504aced8-620aa954-0000-000000000000/"
